lista_compra = ["carne, queso"]
print("Bienvenido a la app de compra online")
import datetime
time = datetime.datetime.now()
mes = str(time.month)
dia = str(time.day)
hora = str(time.hour)
minutos = str(time.minute)
print("Ahora mismmo es: " , time )
print(f"\nAhora mismo tienes {lista_compra} en tu lista de la compra")
comida1= input("¿Que mas desea añadir? ")
lista_compra.append(comida1)
print(f"Acaba de añadir: {comida1}")
comida2= input("¿Que mas desea añadir? ")
lista_compra.append(comida2)
print(f"Acaba de añadir: {comida2}")
comida3= input("¿Que mas desea añadir? ")
lista_compra.append(comida3)
print(f"Acaba de añadir: {comida3}")
print(f"\nSu lista de la compra es {lista_compra}")
print(f"No nos queda {comida3} en la tienda")
comida4= input("\n¿Que otro elemento desea añadir? ")
lista_compra.remove(comida3)
lista_compra.append(comida4)
print(f"\nSu lista de la compra finalmente es {lista_compra} \nMuchas gracias por confiar en nosotros.")