num1= int(input("Hola! Bienvenido \nIngrese la primera nota: "))
num2= int(input("Ingrese el segundo numero: "))
num3= int(input("Ingrese el tercer numero: "))
num4= int(input("Ingrese el cuarto numero: "))
notas= []
notas.append(num1)
notas.append(num2)
notas.append(num3)
notas.append(num4)
print(f"Las notas ingresadas son: {notas}")
rs= sorted(notas,reverse=True)
print(f"Tus notas de mayor a menor son: {rs}")
rs.pop(2)
rs.pop(2)
print(f"Sus notas mas altas son {rs}")
